/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg6_joselagos;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author tali_
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_registro = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jt_fecha = new javax.swing.JTextField();
        jt_pass = new javax.swing.JTextField();
        jt_correo = new javax.swing.JTextField();
        jt_usuario = new javax.swing.JTextField();
        jt_tarjeta = new javax.swing.JTextField();
        jb_registar2 = new javax.swing.JButton();
        jd_pelis = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_personas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_series = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_personas = new javax.swing.JTree();
        jLabel34 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_series = new javax.swing.JTree();
        jd_anadirseries = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jt_duraccion = new javax.swing.JTextField();
        jt_subtitulos = new javax.swing.JTextField();
        jt_idioma = new javax.swing.JTextField();
        jt_categoria = new javax.swing.JTextField();
        jt_numtemp = new javax.swing.JTextField();
        jt_nombre = new javax.swing.JTextField();
        jt_codigo = new javax.swing.JTextField();
        jt_rating = new javax.swing.JTextField();
        jt_productor = new javax.swing.JTextField();
        jt_director = new javax.swing.JTextField();
        jt_actores = new javax.swing.JTextField();
        jb_guardarseries = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jt1_codigo = new javax.swing.JTextField();
        jt1_categoria = new javax.swing.JTextField();
        jt1_idioma = new javax.swing.JTextField();
        jt1_subtitulos = new javax.swing.JTextField();
        jt1_duraccion = new javax.swing.JTextField();
        jt1_nombre = new javax.swing.JTextField();
        jt1_rating = new javax.swing.JTextField();
        jt1_productor = new javax.swing.JTextField();
        jt1_director = new javax.swing.JTextField();
        jt1_actores = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_pelieli = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_serieeli = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jm_eliminar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jm1_eliminar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt_user = new javax.swing.JTextField();
        jp_pass = new javax.swing.JPasswordField();
        jb_ingresar = new javax.swing.JButton();
        jb_registar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("REGISTAR");

        jLabel5.setText("User");

        jLabel6.setText("Correo");

        jLabel7.setText("Contrasena");

        jLabel8.setText("Fecha Nacimiento");

        jLabel9.setText("Tarjeta(Numero)");

        jb_registar2.setText("Registrar");
        jb_registar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registar2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_registroLayout = new javax.swing.GroupLayout(jd_registro.getContentPane());
        jd_registro.getContentPane().setLayout(jd_registroLayout);
        jd_registroLayout.setHorizontalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registroLayout.createSequentialGroup()
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_registroLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel4))
                    .addGroup(jd_registroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_fecha)
                            .addComponent(jt_pass)
                            .addComponent(jt_correo)
                            .addComponent(jt_usuario)
                            .addComponent(jt_tarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_registroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_registar2)
                .addGap(132, 132, 132))
        );
        jd_registroLayout.setVerticalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jt_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jb_registar2)
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setText("PELICULAS  Y SERIES");

        jl_personas.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_personas);

        jl_series.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_series);

        jLabel11.setText("Peliculas");

        jLabel12.setText("Series");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Peliculas");
        jt_personas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane4.setViewportView(jt_personas);

        jLabel34.setText("Peliculas Fav");

        jButton3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton3.setText("FAV");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("FAV");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Series");
        jt_series.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane5.setViewportView(jt_series);

        javax.swing.GroupLayout jd_pelisLayout = new javax.swing.GroupLayout(jd_pelis.getContentPane());
        jd_pelis.getContentPane().setLayout(jd_pelisLayout);
        jd_pelisLayout.setHorizontalGroup(
            jd_pelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_pelisLayout.createSequentialGroup()
                .addGroup(jd_pelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_pelisLayout.createSequentialGroup()
                        .addGroup(jd_pelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_pelisLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel11))
                            .addGroup(jd_pelisLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_pelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jd_pelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_pelisLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12)))
                    .addGroup(jd_pelisLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel10)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jd_pelisLayout.setVerticalGroup(
            jd_pelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_pelisLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(jd_pelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel34)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_pelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_pelisLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(69, 69, 69))
                    .addGroup(jd_pelisLayout.createSequentialGroup()
                        .addGroup(jd_pelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_pelisLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jButton3)))
                        .addContainerGap())))
        );

        jLabel13.setText("Codigo");

        jLabel14.setText("Nombre");

        jLabel15.setText("Numero Temporadas");

        jLabel16.setText("Categoria");

        jLabel17.setText("Idioma");

        jLabel18.setText("Subtitulos");

        jLabel19.setText("Duraccion(Ingrese como double)");

        jLabel20.setText("Rating");

        jLabel21.setText("Productor");

        jLabel22.setText("Director");

        jLabel23.setText("Actores(Separelos por coma)");

        jt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_nombreActionPerformed(evt);
            }
        });

        jb_guardarseries.setText("GUARDAR");
        jb_guardarseries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarseriesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jt_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_productor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_duraccion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_subtitulos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_idioma, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_categoria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_numtemp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_rating, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_codigo)
                            .addComponent(jt_director)
                            .addComponent(jt_actores, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jb_guardarseries)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jt_numtemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jt_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jt_subtitulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jt_duraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jt_rating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jt_productor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jt_director, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jt_actores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_guardarseries)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Anadir Series", jPanel2);

        jLabel24.setText("Codigo");

        jLabel25.setText("Nombre");

        jLabel26.setText("Categoria");

        jLabel27.setText("Idioma");

        jLabel28.setText("Subtitulos");

        jLabel29.setText("Duraccion(Ingrese como double)");

        jLabel30.setText("Rating");

        jLabel31.setText("Productor");

        jLabel32.setText("Director");

        jLabel33.setText("Actores(Separelos por coma)");

        jt1_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt1_categoriaActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt1_duraccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(jt1_subtitulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(jt1_idioma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(jt1_categoria, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jt1_codigo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jt1_nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(jt1_rating, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(jt1_productor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(jt1_director, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(jt1_actores)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jButton2)))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jt1_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jt1_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jt1_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jt1_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jt1_subtitulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jt1_duraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jt1_rating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jt1_productor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jt1_director, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jt1_actores, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Anadir Peliculas", jPanel1);

        jl_pelieli.setModel(new DefaultListModel());
        jl_pelieli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_pelieliMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jl_pelieli);

        jl_serieeli.setModel(new DefaultListModel());
        jl_serieeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_serieeliMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jl_serieeli);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Eliminar Pelicula", jPanel3);

        javax.swing.GroupLayout jd_anadirseriesLayout = new javax.swing.GroupLayout(jd_anadirseries.getContentPane());
        jd_anadirseries.getContentPane().setLayout(jd_anadirseriesLayout);
        jd_anadirseriesLayout.setHorizontalGroup(
            jd_anadirseriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_anadirseriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(27, 27, 27))
        );
        jd_anadirseriesLayout.setVerticalGroup(
            jd_anadirseriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jm_eliminar.setText("ELIMINAR");
        jm_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_eliminarMouseClicked(evt);
            }
        });
        jm_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_eliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jm_eliminar);

        jMenuItem1.setText("jMenuItem1");

        jm1_eliminar.setText("ELIMINAR");
        jm1_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm1_eliminarActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jm1_eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("LOGIN");

        jLabel2.setText("User");

        jLabel3.setText("Password");

        jp_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp_passActionPerformed(evt);
            }
        });

        jb_ingresar.setText("Ingresar");
        jb_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ingresarMouseClicked(evt);
            }
        });

        jb_registar.setText("Registar");
        jb_registar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registarMouseClicked(evt);
            }
        });

        jButton1.setText("ADMIN");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jp_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_ingresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_registar)
                        .addGap(93, 93, 93))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jp_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_ingresar)
                    .addComponent(jb_registar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jp_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jp_passActionPerformed

    private void jb_registar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registar2MouseClicked
        Registro();
    }//GEN-LAST:event_jb_registar2MouseClicked

    private void jb_registarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registarMouseClicked
        jd_registro.setModal(true);
        jd_registro.pack();
        jd_registro.setLocationRelativeTo(this);
        jd_registro.setVisible(true);
    }//GEN-LAST:event_jb_registarMouseClicked

    private void jb_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ingresarMouseClicked
        Scanner sc = null;
        File archivito = null;
        boolean v = false;
        c = 0;
        try {
            archivito = new File("./user.txt");
            sc = new Scanner(archivito);
            DefaultListModel modelo = (DefaultListModel) jl_personas.getModel();
            DefaultTreeModel modeloARBOL1 = (DefaultTreeModel) jt_series.getModel();
        DefaultMutableTreeNode raiz1 = (DefaultMutableTreeNode) modeloARBOL1.getRoot();
            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_personas.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            DefaultListModel modelo1 = (DefaultListModel) jl_series.getModel();
            modelo1.clear();
            sc.useDelimiter(";");
            modelo.clear();
            modeloARBOL.reload();
            while (sc.hasNext()) {
                String name = sc.next();
                String pass = sc.next();
                if (name.equals(jt_user.getText()) && pass.equals(jp_pass.getText())) {
                    v = true;
                    File archivo = new File("./peliculas.txt");
                    Scanner sc2 = new Scanner(archivo);
                    sc2.useDelimiter(";");
                    while (sc2.hasNext()) {
                        String code = sc2.next();
                        String peli = sc2.next();
                        String cate = sc2.next();
                        String idiomas = sc2.next();
                        String sub = sc2.next();
                        double time = sc2.nextDouble();
                        int rate = sc2.nextInt();
                        String com = sc2.next();
                        String prod = sc2.next();
                        String direct = sc2.next();
                        String actores = sc2.next();
                        modelo.addElement(new Peliculas(code, peli, cate, time, rate, prod, direct));
                        String name2 = ((Peliculas) modelo.get(0)).getNombre();
                        jl_personas.setModel(modelo);
                        for (int a = 0; a < users.get(c).getFav().size(); a++) {
                            String categoria, nombre;
                            int rating;
                            categoria = users.get(c).getFav().get(a).getCategoria();
                            nombre = users.get(c).getFav().get(a).getNombre();
                            rating = users.get(c).getFav().get(a).getRating();
                            String id = users.get(c).getFav().get(a).getId();
                            double duracion = users.get(c).getFav().get(a).getDuracion();
                            String productora = users.get(c).getFav().get(a).getProductora();
                            String director = users.get(c).getFav().get(a).getDirector();
                            int centinela = -1;
                            for (int i = 0; i < raiz.getChildCount(); i++) {
                                if (raiz.getChildAt(i).toString().equals(categoria)) {
                                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Peliculas(id, nombre, categoria, duracion, rating, productora, director));
                                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                                    centinela = 1;
                                }
                            }
                            if (centinela == -1) {
                                DefaultMutableTreeNode n = new DefaultMutableTreeNode(categoria);
                                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Peliculas(id, nombre, categoria, duracion, rating, productora, director));
                                n.add(p);
                                raiz.add(n);
                            }
                            modeloARBOL.reload();
                        }
                    }
                    File archivo2 = new File("./series.txt");
                    Scanner sc3 = new Scanner(archivo2);
                    sc3.useDelimiter(";");
                    while (sc3.hasNext()) {
                        String code = sc3.next();
                        String peli = sc3.next();
                        int temp = sc3.nextInt();
                        String cate = sc3.next();
                        String idiomas = sc3.next();
                        String sub = sc3.next();
                        double time = sc3.nextDouble();
                        int rate = sc3.nextInt();
                        String com = sc3.next();
                        String prod = sc3.next();
                        String direct = sc3.next();
                        String actores = sc3.next();

                        modelo1.addElement(new Series(code, peli, cate, time, rate, prod, direct, temp));
                        jl_series.setModel(modelo1);
                        for (int a = 0; a < users.get(c).getFavo().size(); a++) {
                            String categoria = users.get(c).getFavo().get(a).getCategoria();
                            String nombre = users.get(c).getFavo().get(a).getNombre();
                            int rating = users.get(c).getFavo().get(a).getRating();
                            String id = users.get(c).getFavo().get(a).getId();
                            double duracion = users.get(c).getFavo().get(a).getDuracion();
                            String productora = users.get(c).getFavo().get(a).getProductora();
                            String director = users.get(c).getFavo().get(a).getDirector();
                            int temp2 = users.get(c).getFavo().get(a).getTemp();
                            int centinela = -1;
                            for (int i = 0; i < raiz1.getChildCount(); i++) {
                                if (raiz1.getChildAt(i).toString().equals(categoria)) {
                                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Series(id, nombre, categoria, duracion, rating, productora, director, temp));
                                    ((DefaultMutableTreeNode) raiz1.getChildAt(i)).add(p);
                                    centinela = 1;
                                }
                            }
                            if (centinela == -1) {
                                DefaultMutableTreeNode n = new DefaultMutableTreeNode(categoria);
                                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Series(id, nombre, categoria, duracion, rating, productora, director, temp));
                                n.add(p);
                                raiz1.add(n);
                            }
                            modeloARBOL1.reload();

                        }

                    }
                    jd_pelis.setModal(true);
                    jd_pelis.pack();
                    jd_pelis.setLocationRelativeTo(this);
                    jd_pelis.setVisible(true);
                    break;
                }
                sc.next();
                sc.next();
                sc.next();
                c++;
            }
            if (v == false) {
                JOptionPane.showMessageDialog(this, "NO EXISTE ESE USUARIO");
            }
            sc.close();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_ingresarMouseClicked

    private void jt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_nombreActionPerformed

    private void jb_guardarseriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarseriesMouseClicked
        File archivito = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            archivito = new File("./series.txt");
            fw = new FileWriter(archivito, true);
            bw = new BufferedWriter(fw);
            bw.write(jt_codigo.getText() + ";");
            bw.write(jt_nombre.getText() + ";");
            bw.write(jt_numtemp.getText() + ";");
            bw.write(jt_categoria.getText() + ";");
            bw.write(jt_idioma.getText() + ";");
            bw.write(jt_subtitulos.getText() + ";");
            bw.write(jt_duraccion.getText() + ";");
            bw.write(jt_rating.getText() + ";");
            bw.write("mala" + ";");
            bw.write(jt_productor.getText() + ";");
            bw.write(jt_director.getText() + ";");
            bw.write(jt_actores.getText() + ";");
            bw.flush();
            jt_codigo.setText("");
            jt_numtemp.setText("");
            jt_categoria.setText("");
            jt_idioma.setText("");
            jt_subtitulos.setText("");
            jt_duraccion.setText("");
            jt_rating.setText("");
            jt_productor.setText("");
            jt_director.setText("");
            jt_actores.setText("");
            jt_nombre.setText("");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_guardarseriesMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            File archivo = new File("./peliculas.txt");
            Scanner sc2 = new Scanner(archivo);
            sc2.useDelimiter(";");
            while (sc2.hasNext()) {
                String code = sc2.next();
                String peli = sc2.next();
                String cate = sc2.next();
                String idiomas = sc2.next();
                String sub = sc2.next();
                double time = sc2.nextDouble();
                int rate = sc2.nextInt();
                String com = sc2.next();
                String prod = sc2.next();
                String direct = sc2.next();
                String actores = sc2.next();
                DefaultListModel modelo = (DefaultListModel) jl_pelieli.getModel();
                modelo.addElement(new Peliculas(code, peli, cate, time, rate, prod, direct));
                String name2 = ((Peliculas) modelo.get(0)).getNombre();
                System.out.println(name2);
                jl_pelieli.setModel(modelo);

            }
            File archivo2 = new File("./series.txt");
            Scanner sc3 = new Scanner(archivo2);
            sc3.useDelimiter(";");
            while (sc3.hasNext()) {
                String code = sc3.next();
                String peli = sc3.next();
                int temp = sc3.nextInt();
                String cate = sc3.next();
                String idiomas = sc3.next();
                String sub = sc3.next();
                double time = sc3.nextDouble();
                int rate = sc3.nextInt();
                String com = sc3.next();
                String prod = sc3.next();
                String direct = sc3.next();
                String actores = sc3.next();
                DefaultListModel modelo = (DefaultListModel) jl_serieeli.getModel();
                modelo.addElement(new Series(code, peli, cate, time, rate, prod, direct, temp));
                jl_serieeli.setModel(modelo);
            }
        } catch (Exception e) {
        }
        jd_anadirseries.setModal(true);
        jd_anadirseries.pack();
        jd_anadirseries.setLocationRelativeTo(this);
        jd_anadirseries.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jt1_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt1_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt1_categoriaActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        File archivito = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            archivito = new File("./peliculas.txt");
            fw = new FileWriter(archivito, true);
            bw = new BufferedWriter(fw);
            bw.write(jt1_codigo.getText() + ";");
            bw.write(jt1_nombre.getText() + ";");
            bw.write(jt1_categoria.getText() + ";");
            bw.write(jt1_idioma.getText() + ";");
            bw.write(jt1_subtitulos.getText() + ";");
            bw.write(jt1_duraccion.getText() + ";");
            bw.write(jt1_rating.getText() + ";");
            bw.write("mala" + ";");
            bw.write(jt1_productor.getText() + ";");
            bw.write(jt1_director.getText() + ";");
            bw.write(jt1_actores.getText() + ";");
            bw.flush();
            jt1_codigo.setText("");
            jt1_categoria.setText("");
            jt1_idioma.setText("");
            jt1_subtitulos.setText("");
            jt1_duraccion.setText("");
            jt1_rating.setText("");
            jt1_productor.setText("");
            jt1_director.setText("");
            jt1_actores.setText("");
            jt1_nombre.setText("");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_personas.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
        if (jl_personas.getSelectedIndex() >= 0) {
            modeloARBOL = (DefaultTreeModel) jt_personas.getModel();
            raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            //obtener la persona a guardar
            DefaultListModel modeloLISTA = (DefaultListModel) jl_personas.getModel();
            String categoria, nombre;
            int rating;
            categoria = ((Peliculas) modeloLISTA.get(jl_personas.getSelectedIndex())).getCategoria();
            nombre = ((Peliculas) modeloLISTA.get(jl_personas.getSelectedIndex())).getNombre();
            rating = ((Peliculas) modeloLISTA.get(jl_personas.getSelectedIndex())).getRating();
            String id = ((Peliculas) modeloLISTA.get(jl_personas.getSelectedIndex())).getId();
            double duracion = ((Peliculas) modeloLISTA.get(jl_personas.getSelectedIndex())).getDuracion();
            String productora = ((Peliculas) modeloLISTA.get(jl_personas.getSelectedIndex())).getProductora();
            String director = ((Peliculas) modeloLISTA.get(jl_personas.getSelectedIndex())).getDirector();
            users.get(c).getFav().add(new Peliculas(id, nombre, categoria, duracion, rating, productora, director));
            try {
                escribirArchivo();
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(categoria)) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Peliculas(id, nombre, categoria, duracion, rating, productora, director));
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                    centinela = 1;
                }
            }
            if (centinela == -1) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(categoria);
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Peliculas(id, nombre, categoria, duracion, rating, productora, director));
                n.add(p);
                raiz.add(n);
            }
            modeloARBOL.reload();
        } else {
            JOptionPane.showMessageDialog(this, "No hay persona seleccionada");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_series.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
        if (jl_series.getSelectedIndex() >= 0) {
            modeloARBOL = (DefaultTreeModel) jt_series.getModel();
            raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            //obtener la persona a guardar
            DefaultListModel modeloLISTA = (DefaultListModel) jl_series.getModel();
            String categoria, nombre;
            int rating;
            categoria = ((Series) modeloLISTA.get(jl_series.getSelectedIndex())).getCategoria();
            nombre = ((Series) modeloLISTA.get(jl_series.getSelectedIndex())).getNombre();
            rating = ((Series) modeloLISTA.get(jl_series.getSelectedIndex())).getRating();
            String id = ((Series) modeloLISTA.get(jl_series.getSelectedIndex())).getId();
            double duracion = ((Series) modeloLISTA.get(jl_series.getSelectedIndex())).getDuracion();
            String productora = ((Series) modeloLISTA.get(jl_series.getSelectedIndex())).getProductora();
            String director = ((Series) modeloLISTA.get(jl_series.getSelectedIndex())).getDirector();
            int temp = ((Series) modeloLISTA.get(jl_series.getSelectedIndex())).getTemp();
            users.get(c).getFavo().add(new Series(id, nombre, categoria, duracion, rating, productora, director, temp));
            try {
                escribirArchivo();
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }

            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(categoria)) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Series(id, nombre, categoria, duracion, rating, productora, director, temp));
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                    centinela = 1;
                }
            }
            if (centinela == -1) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(categoria);
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Series(id, nombre, categoria, duracion, rating, productora, director, temp));
                n.add(p);
                raiz.add(n);
            }
            modeloARBOL.reload();
        } else {
            JOptionPane.showMessageDialog(this, "No hay persona seleccionada");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jl_pelieliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_pelieliMouseClicked
        jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_jl_pelieliMouseClicked

    private void jm_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_eliminarMouseClicked
        if (jl_pelieli.getSelectedIndex() >= 0) {
            Peliculas Persona = new Peliculas();
            DefaultListModel modeloLISTA = (DefaultListModel) jl_pelieli.getModel();
            String name = ((Peliculas) modeloLISTA.get(jl_personas.getSelectedIndex())).getNombre();
            modeloLISTA.remove(jl_pelieli.getSelectedIndex());

        }
    }//GEN-LAST:event_jm_eliminarMouseClicked

    private void jm_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_eliminarActionPerformed
        if (jl_pelieli.getSelectedIndex() >= 0) {
            Peliculas Persona = new Peliculas();
            DefaultListModel modeloLISTA = (DefaultListModel) jl_pelieli.getModel();
            modeloLISTA.remove(jl_pelieli.getSelectedIndex());
        }
    }//GEN-LAST:event_jm_eliminarActionPerformed

    private void jl_serieeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_serieeliMouseClicked

        jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());

    }//GEN-LAST:event_jl_serieeliMouseClicked

    private void jm1_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm1_eliminarActionPerformed
        if (jl_pelieli.getSelectedIndex() >= 0) {
            Series Series = new Series();
            DefaultListModel modeloLISTA = (DefaultListModel) jl_serieeli.getModel();
            modeloLISTA.remove(jl_serieeli.getSelectedIndex());
        }
    }//GEN-LAST:event_jm1_eliminarActionPerformed
    public void Registro() {
        File archivito = null;
        Scanner sc = null;
        FileWriter fw = null;
        BufferedWriter bw = null;

        try {
            archivito = new File("./user.txt");
            fw = new FileWriter(archivito, true);
            bw = new BufferedWriter(fw);
            users.add(new Usuarios(jt_usuario.getText(), jt_correo.getText(), jt_pass.getText(), jt_fecha.getText(), jt_tarjeta.getText()));
            escribirArchivo();
            jd_registro.setVisible(false);
        } catch (Exception e) {
        }
    }

    public void escribirArchivo() throws IOException {
        FileWriter fw = null;
        BufferedWriter bw = null;

        try {
            File archivo = new File("./user.txt");
            fw = new FileWriter(archivo, false);
            bw = new BufferedWriter(fw);
            for (Usuarios t : users) {
                bw.write(t.getUser() + ";");
                bw.write(t.getContra() + ";");
                bw.write(t.getCorreo() + ";");

                for (Peliculas h : t.getFav()) {

                    bw.write(h.getId() + ",");
                }
                bw.write(";");
                for (Series h : t.getFavo()) {
                    bw.write(h.getId() + ",");
                }
                bw.write(";");
            }
            bw.flush();
        } catch (Exception e) {
        }
        bw.close();
        fw.close();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_guardarseries;
    private javax.swing.JButton jb_ingresar;
    private javax.swing.JButton jb_registar;
    private javax.swing.JButton jb_registar2;
    private javax.swing.JDialog jd_anadirseries;
    private javax.swing.JDialog jd_pelis;
    private javax.swing.JDialog jd_registro;
    private javax.swing.JList<String> jl_pelieli;
    private javax.swing.JList<String> jl_personas;
    private javax.swing.JList<String> jl_serieeli;
    private javax.swing.JList<String> jl_series;
    private javax.swing.JMenuItem jm1_eliminar;
    private javax.swing.JMenuItem jm_eliminar;
    private javax.swing.JPasswordField jp_pass;
    private javax.swing.JTextField jt1_actores;
    private javax.swing.JTextField jt1_categoria;
    private javax.swing.JTextField jt1_codigo;
    private javax.swing.JTextField jt1_director;
    private javax.swing.JTextField jt1_duraccion;
    private javax.swing.JTextField jt1_idioma;
    private javax.swing.JTextField jt1_nombre;
    private javax.swing.JTextField jt1_productor;
    private javax.swing.JTextField jt1_rating;
    private javax.swing.JTextField jt1_subtitulos;
    private javax.swing.JTextField jt_actores;
    private javax.swing.JTextField jt_categoria;
    private javax.swing.JTextField jt_codigo;
    private javax.swing.JTextField jt_correo;
    private javax.swing.JTextField jt_director;
    private javax.swing.JTextField jt_duraccion;
    private javax.swing.JTextField jt_fecha;
    private javax.swing.JTextField jt_idioma;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTextField jt_numtemp;
    private javax.swing.JTextField jt_pass;
    private javax.swing.JTree jt_personas;
    private javax.swing.JTextField jt_productor;
    private javax.swing.JTextField jt_rating;
    private javax.swing.JTree jt_series;
    private javax.swing.JTextField jt_subtitulos;
    private javax.swing.JTextField jt_tarjeta;
    private javax.swing.JTextField jt_user;
    private javax.swing.JTextField jt_usuario;
    // End of variables declaration//GEN-END:variables
    Usuarios u = new Usuarios();
    ArrayList<Usuarios> users = new ArrayList();
    int c;
}
